image: Visual Studio 2019

branches:
  only:
    - master

platform:
  - Win32
  - x64
  
configuration:
  - Release
  - Debug

install:
  - git submodule init
  - git submodule update

before_build:
  - mkdir build
  - cmake -S . -B build

build_script:
  - cmake --build build

build:
  project: build/v1.sln