image: Visual Studio 2019

platform:
  - x64
  - x86

configuration:
    # ... и в дебажной, и в релизной конфигурациях ...
    - Release
    - Debug


# environment:
#   matrix:
#     - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#       GENERATOR: "Visual Studio 14 2015"
#       CONFIG: Debug

#     - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#       GENERATOR: "Visual Studio 16 2019"
#       CONFIG: Release
#       ARCH_ARG: "-A x64"

install:
  - git submodule init
  - git submodule update

before_build:
  - mkdir build
  - cmake -S . -B build
  - cmake --build build

build:
  project: build/v1.sln