environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 14 2015"
      CONFIG: Debug

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: "Visual Studio 16 2019"
      CONFIG: Release
      ARCH_ARG: "-A x64"

build_script:
  - git submodule init
  - git submodule update
  - mkdir build
  - cmake -G "%GENERATOR%" -S . -B build
  - cmake --build build --config "%CONFIG%"