image: Visual Studio 2015  # образ для сборки

language: cpp

compiler:
  - gcc

before_script:
  - git submodule init
  - git submodule update
  - mkdir build
  - cmake -G 'MinGW Makefiles' -S . -B build

script: cmake --build build